AppBundle\Entity\Curso:
  properties:
    titulo:
      - NotBlank: {message: "El título no puede estar vacío"}
      - Length:
          min: 2
          minMessage: "El título debe tener mas de dos caracteres"
    descripcion:
      - NotBlank: {message: "La descripción no puede estar vacía"}
    precio:
      - Type:
          type: float
          message: "El precio tiene que ser numérico"